name: go-arch
services:
  web:
    build:
      context: ./web
      target: final
    expose:
      - 8080
    environment:
      - SEARCH_ADDR=micro:4000
    scale: 2
    depends_on:
      - micro

  micro:
    build:
      context: ./micro
      target: final
    expose:
      - 4000

  reverse-proxy:
    image: nginx
    ports:
      - 4433:4433
    volumes:
      - ./etc/certs:/etc/nginx/certs
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
